config/routes.rb
Rails.application.routes.draw do
  root 'users#show'
  resources :items
  resources :users, except: [:new, :show] do
    resources :shopping_lists,  except: [:new, :create]
    resources :events
    get '/hosted', to: 'events#hosted'
  end
  resources :amounts, only: :destroy
  get '/signup', to: 'users#new'
  get '/profile', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/facebook/callback', to: 'sessions#create_fb'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :user_events
  has_many :events, through: :user_events
  has_many :hosted_events, foreign_key: :host_id, class_name: "Event"
  has_many :shopping_lists, through: :hosted_events

  validates :name, presence: true
  validates :name, uniqueness: true

  def attended_events
    self.events.select{|event| !self.hosted_events.include?(event)}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    redirect_if_not_logged_in
    @users = User.all
  end

  def show
    @user = current_user
    redirect_if_not_logged_in
  end

  def new
    redirect_if_logged_in
    @user = User.new
  end

  def create
    redirect_if_logged_in
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to '/profile', alert: "Welcome"
    else
      render :new
    end
  end

  def edit
    redirect_if_not_logged_in
    redirect_if_user_doesnt_match(params[:id])
    @user = find_user
  end

  def update
    redirect_if_not_logged_in
    if @user = User.update(user_params)
      redirect_to '/profile'
    else
      render :edit
    end
  end

  def destroy
    redirect_if_not_logged_in
    redirect_if_user_doesnt_match(params[:id])
    user = find_user
    user.destroy
  end

  private

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :birthday)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%=form_for @user do |f| %>
  <%=f.label :name%>
  <%=f.text_field :name%><br>
  <%=f.label :password%>
  <%=f.password_field :password%><br>
  <%=f.label :password_confirmation%>
  <%=f.password_field :password_confirmation%><br>
  <%=f.label :birthday%>
  <%=f.date_field :birthday, max: "2021-12-31", min: "1920-12-31"%><br>
  <%=f.submit%>
<%end%>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render partial: "form"%>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <% if current_user == user %>
    <h3><%= link_to "Me", '/profile' %></h3>
  <% else %>
    <h3><%= user.name %></h3>
  <% end %>
  <ul>
    <li>Hosting <%= user.hosted_events.count %> event(s)</li>
    <li>Attending <%= user.events.count %> event(s)</li>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1>Create an Account:</h1>
<%= render partial: "form"%>

app/views/users/show.html.erb
<h1><%=@user.name%></h1>

<h2><%=link_to "Your Shopping Lists", user_shopping_lists_path(@user)%></h2>
<% @user.shopping_lists.each do |list| %>
  <%= link_to list.name, user_shopping_list_path(@user, list) %>
<% end %>

<h2><%=link_to "Events You're Hosting", user_hosted_path(@user)%></h2>
<%=render partial: "/events/show_events", locals: {events: @user.hosted_events, user: @user}%>
<%= link_to "Create a New Event", new_user_event_path(@user)%>

<h2><%=link_to "Events You're Attending", user_events_path(@user)%></h2>
<%=render partial: "/events/show_events", locals: {events: @user.attended_events, user: @user}%>