config/routes.rb
Rails.application.routes.draw do
  root 'users#show'
  resources :items
  resources :users, except: [:new, :show] do
    resources :shopping_lists,  except: [:new, :create]
    resources :events
    get '/hosted', to: 'events#hosted'
  end
  resources :amounts, only: :destroy
  get '/signup', to: 'users#new'
  get '/profile', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/facebook/callback', to: 'sessions#create_fb'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_one :shopping_list
  has_many :user_events
  has_many :users, through: :user_events
  belongs_to :host, class_name: "User"

  scope :hosted, ->(var) {where(host_id: var)}
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    #checks to see if the user is logged in and is the same user in the url /users/**here**/events
    redirect_if_not_logged_in
    redirect_if_user_doesnt_match(params[:user_id])

    #gets all of the current_user's events
    @events = current_user.events
    @user = current_user
  end

  def hosted
    #same checks as index action
    redirect_if_not_logged_in
    redirect_if_user_doesnt_match(params[:user_id])

    #gets the events hosted by current_user
    @events = Event.hosted(current_user.id)
    @user = current_user
  end

  def show
    #same checks as index action + checks to make sure the user is attending the event
    redirect_if_not_logged_in
    redirect_if_user_doesnt_match(params[:user_id])
    redirect_if_not_attending

    #gets event for view
    @event = find_event
    @user = current_user
  end

  def new
    redirect_if_not_logged_in
    @event = Event.new
    @user = current_user
    @users = User.all
  end

  def create
    event = Event.create(event_params)
    event.users << current_user unless event.users.include?(current_user)
    event.shopping_list = ShoppingList.create(name: "#{event.name}'s Shopping List")
    event.save
    redirect_to user_event_path(current_user, event), alert: "successfully created event"
  end

  def edit
    redirect_if_not_logged_in
    redirect_if_user_doesnt_match(params[:user_id])
    @event = find_event
    @user = current_user
    @users = User.all
  end

  def update
    event = find_event
    redirect_to "/users/#{session[:user_id]}/events" unless event
    redirect_to "/users/#{session[:user_id]}/events" unless event.host == current_user
    event.update(event_params)
    redirect_to user_event_path(current_user, event), alert: "successfully changed event"
  end

  def destroy
    redirect_if_not_logged_in
    event = find_event
    redirect_if_user_doesnt_match(event.id)

    event.destroy
    redirect_to '/profile', alert: "event successfully destroyed"
  end

  private

    def redirect_if_not_attending
      redirect_to "/users/#{session[:user_id]}/events" unless Event.find_by(id: params[:id]).users.include?(current_user)
    end

    def find_event
      Event.find_by(id: params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :time, :host_id, :location, user_ids: [])
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_time(event)
    event.time.strftime("%A, %B %e %l:%M%P")
  end
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%=form_for @event, url: post_url do |f| %>
  <%=f.hidden_field :host_id, value: @user.id%>
  <%=f.label :name%>
  <%=f.text_field :name%><br>
  <%=f.label :location%>
  <%=f.text_field :location%><br>
  <%=f.label :time%>
  <%=f.datetime_field :time, min: DateTime.current.noon%><br>
  <%=f.collection_check_boxes :user_ids, @users, :id, :name%>
  <%=f.submit%>
<%end%>

app/views/events/_show_event.html.erb
<% events.each do |event| %>
  <h3><%= link_to event.name, event_path(event) %></h3>
  <ul>
    <li><%= event.location %></li>
    <li><%= event_time %></li>
  </ul>
<% end %>

app/views/events/_show_events.html.erb
<% events.each do |event| %>
  <h3><%= link_to event.name, user_event_path(user, event) %></h3>
  <ul>
    <li><%= event.location %></li>
    <li><%= event_time(event) %></li>
  </ul>
<% end %>

app/views/events/edit.html.erb
<% redirect_to "/users/#{@user.id}/events", alert: "Must be the host to edit an event" if current_user != @event.host %>

<h1>Edit event</h1>
<%= render partial: "form", locals: {post_url: "/users/#{@user.id}/events/#{@event.id}"} %>

app/views/events/hosted.html.erb
<h1>Hosted Events: </h1>
<%=render partial: "show_events", locals: {events: @events, user: @user}%>
<%= link_to "Add Event", new_user_event_path(@user) %>

app/views/events/index.html.erb
<h1>All Events: </h1>
<%=render partial: "show_events", locals: {events: @events, user: @user}%>

app/views/events/new.html.erb
<h1>Create an event</h1>
<%= render partial: "form", locals: {post_url: "/users/#{@user.id}/events"} %>

app/views/events/show.html.erb
<h3>Event:</h3>
<%= @event.name %><br>
<h3>Host:</h3>
<%= @event.host.name %><br>
<h3>Time:</h3>
<%= event_time(@event) %><br>
<h3>Location:</h3>
<%= @event.location %><br>
<h3>Attendees:</h3>
<ul>
  <% @event.users.each do |user|%>
    <li><%= user.name %></li>
  <%end%><br>
</ul>
<% if @event.host == @user %>
  <h3><%= link_to "Shopping List:", user_shopping_list_path(@user, @event.shopping_list)%></h3>
  <% if @event.shopping_list.items.empty? %>
    <%= link_to "Add items now", edit_user_shopping_list_path(@user, @event.shopping_list) %>
  <%else%>
    <% @event.shopping_list.items.each do |item| %>
      <%= item.name %>
    <% end %>
  <% end %>

  <%= button_to "Delete this Event", user_event_path(@event), method: :delete %>
<% end %>