config/routes.rb
Rails.application.routes.draw do
  root 'users#show'
  resources :items
  resources :users, except: [:new, :show] do
    resources :shopping_lists,  except: [:new, :create]
    resources :events
    get '/hosted', to: 'events#hosted'
  end
  resources :amounts, only: :destroy
  get '/signup', to: 'users#new'
  get '/profile', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/facebook/callback', to: 'sessions#create_fb'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :amounts
  has_many :shopping_lists, through: :amounts
  belongs_to :category
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    redirect_if_not_logged_in
    @items = {}
    @categories = Category.all
    @categories.each do |category|
      @items["#{category.name}"] = category.items
    end
  end

  def show
    redirect_if_not_logged_in
    @item = Item.find_by(id: params[:id])
  end

  def new
    redirect_if_not_logged_in
    @item = Item.new
    @categories = Category.all
  end

  def create
    redirect_if_not_logged_in
    item = Item.create(item_params)
    redirect_to item, alert: "Successfully created item."
  end

  def edit
    redirect_if_not_logged_in
    @item = Item.find_by(id: params[:id])
    @categories = Category.all
  end

  def update
    redirect_if_not_logged_in
    item = Item.find_by(id: params[:id])
    item.update(item_params)
    redirect_to item, alert: "Successfully updated item."
  end

  def destroy
    redirect_if_not_logged_in
    item = Item.find_by(id: params[:id])
    name = item.name
    item.destroy
    redirect_to items_path, alert: "Successfully destroyed item: #{name}"
  end

  private

    def item_params
      params.require(:item).permit(:name, :description, :category_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @item do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.label :category %><br>
  <%= f.collection_radio_buttons :category_id, @categories, :id, :name %>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Edit <%= @item.name %></h1>
<%= render partial: "form" %>

app/views/items/index.html.erb
<h1>All Items:</h1>
<% @categories.each do |category| %>
  <h3><%= category.name %></h3>
  <ul>
    <% @items["#{category.name}"].sort{|a,b| a.name <=> b.name}.each do |item| %>
      <li><%= link_to item.name, item_path(item) %></li>
    <% end %>
  </ul>
<% end %>

app/views/items/new.html.erb
<h1>Create an Item:</h1>
<%= render partial: "form" %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<h3><%= @item.category.name %></h3>
<h4><%= @item.description %></h4>
<%= link_to "Edit Item", edit_item_path(@item) %>
<%= button_to "Delete Item", item_path(@item), method: :delete %>