config/routes.rb
Rails.application.routes.draw do
  root 'users#show'
  resources :items
  resources :users, except: [:new, :show] do
    resources :shopping_lists,  except: [:new, :create]
    resources :events
    get '/hosted', to: 'events#hosted'
  end
  resources :amounts, only: :destroy
  get '/signup', to: 'users#new'
  get '/profile', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/facebook/callback', to: 'sessions#create_fb'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductivityApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <nav>
      <% if current_user %>
        <%= link_to "Profile", '/profile', class: "navbar" %>
        <%= link_to "Users", users_path, class: "navbar" %>
        <%= link_to "Shopping Lists", user_shopping_lists_path(current_user), class: "navbar" %>
        <%= link_to "Events", user_events_path(current_user), class: "navbar" %>
        <%= link_to "Hosted Events", user_hosted_path(current_user), class: "navbar" %>
        <%= link_to "Items", items_path, class: "navbar" %>
        <%= button_to "Log Out", '/logout', method: :delete, id: "logout", class: "navbar" %>
      <% else %>
        <%= link_to "Sign up", '/signup', class: "navbar" %>
        <%= link_to "Sign In", '/login', class: "navbar" %>
      <% end %>
    </nav>
    <% if flash[:alert] %>
      <div class="alert">
        <h3><%= flash[:alert] %></h3>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>